[PT-5] network
ibondarovich/FoodApp pull request #8
Opened 2023-08-04 13:54 UTC by ibondarovich

add authentication service for cheking user status
add sign in with google
add sign in with email and password
add sign up
add sign out
update navigation
add sign out to settings screen
add sign in and sign up screens

https://github.com/ibondarovich/FoodApp/assets/92872368/6257430d-7bd9-4880-a2e0-54d9f751f834

2023-08-07 14:26 UTC, Alexey-Lebedzeu requested changes

2023-08-07 14:26 UTC, Alexey-Lebedzeu commented on core_ui/lib/src/theme/app_dimens.dart
> +  static const List<double> textScales = [0.7, 1, 1.5];
enum

2023-08-07 14:26 UTC, Alexey-Lebedzeu commented on data/lib/providers/local/local_provider.dart
>    bool getTheme();
saparate

2023-08-07 14:26 UTC, Alexey-Lebedzeu commented on data/lib/repositories/settings_repository_impl.dart
> +    return _localProvider.getScaleFactor();
check naming

2023-08-07 14:26 UTC, Alexey-Lebedzeu commented on domain/lib/repositories/user_repository.dart
> +  bool checkUser();
naming

2023-08-07 14:26 UTC, Alexey-Lebedzeu commented on features/authentication_view/lib/src/ui/auth_screen.dart
> +          'assets/img/logo.png',
???

2023-08-07 14:26 UTC, Alexey-Lebedzeu commented on features/authentication_view/lib/src/ui/auth_screen.dart
> +                  SnackBar(
to core UI

2023-08-09 14:20 UTC, dungeon-slave commented on core/lib/constants/string_constants.dart
> +  static const String hiveBoxUser = 'User';
naimng

2023-08-09 14:21 UTC, dungeon-slave commented on core/lib/enums/text_scale_enum.dart
> +}
formatting

2023-08-09 14:23 UTC, dungeon-slave commented on core/lib/validation/validation.dart
> +    return 'Please enter an email';
hardcode

2023-08-09 14:28 UTC, dungeon-slave commented on core_ui/lib/src/widgets/app_image.dart
> +  final String filePath;
make private

2023-08-09 14:28 UTC, dungeon-slave commented on core_ui/lib/src/widgets/app_image_button.dart
> +  final String title;
make private

2023-08-09 14:31 UTC, dungeon-slave commented on core_ui/lib/src/widgets/app_snackbar.dart
> +void showAppSnackBar({
make widget

2023-08-09 14:45 UTC, dungeon-slave commented on data/lib/providers/local/cart_data_provider_impl.dart
> +}
formatting

2023-08-09 14:45 UTC, dungeon-slave commented on data/lib/providers/local/dish_data_provider.dart
> +}
formatting

2023-08-09 14:46 UTC, dungeon-slave commented on data/lib/providers/local/dish_data_provider_impl.dart
> +        input.map((item) async => await menuHiveBox.put(item.id, item)));
,
type

2023-08-09 14:47 UTC, dungeon-slave commented on data/lib/providers/local/theme_data_provider.dart
> +}
formatting

2023-08-09 14:48 UTC, dungeon-slave commented on data/lib/providers/local/theme_data_provider_impl.dart
> +  final Box<bool> settingsHiveBox;
make private

2023-08-09 14:48 UTC, dungeon-slave commented on data/lib/providers/local/user_data_provider.dart
> +}
formatting

2023-08-09 14:48 UTC, dungeon-slave commented on data/lib/providers/local/user_data_provider_impl.dart
> +  final Box<String> userHiveBox;
make private

2023-08-09 14:50 UTC, dungeon-slave commented on data/lib/repositories/cart_repository_impl.dart
>      return response.map((entity) => CartItemMapper.toModel(entity)).toList();
type

2023-08-09 14:53 UTC, dungeon-slave commented on features/authentication_view/lib/authentication_view.dart
> +export 'src/ui/auth_screen.dart';
formatting

2023-08-09 14:54 UTC, dungeon-slave commented on features/authentication_view/lib/src/bloc/bloc/bloc.dart
> +        isValidated(state.emailValidationError, state.passwordValidationError);
,

2023-08-09 14:57 UTC, dungeon-slave commented on features/authentication_view/lib/src/ui/auth_screen.dart
> +          scale: 2,
hardcode

2023-08-09 14:57 UTC, dungeon-slave commented on features/authentication_view/lib/src/ui/components/app_text_field.dart
> +  final String? hintText;
make private

2023-08-09 14:57 UTC, dungeon-slave commented on features/authentication_view/lib/src/ui/components/header.dart
> +  final String mainTitle;
make private

2023-08-09 14:58 UTC, dungeon-slave commented on features/authentication_view/lib/src/ui/components/login.dart
> +  TextEditingController emailController = TextEditingController();
private

2023-08-09 14:59 UTC, dungeon-slave commented on features/authentication_view/lib/src/ui/components/login.dart
> +                            OnEmailChanged(value: value),
remove ,

2023-08-09 14:59 UTC, dungeon-slave commented on features/authentication_view/lib/src/ui/components/login.dart
> +                            OnPasswordChanged(value: value),
remove ,

2023-08-09 15:03 UTC, dungeon-slave commented on features/authentication_view/lib/src/ui/components/signup.dart
> +  TextEditingController emailController = TextEditingController();
private

2023-08-09 15:05 UTC, dungeon-slave commented on features/main_view/lib/main_view.dart
> +export 'src/ui/main_view_screen.dart';
formatting

2023-08-09 15:09 UTC, dungeon-slave commented on navigation/lib/src/app_router/app_router.dart
> +}
formatting

2023-08-10 13:48 UTC, Alexey-Lebedzeu commented on features/authentication_view/lib/src/ui/components/login.dart
> +  TextEditingController emailController = TextEditingController();
final

2023-08-10 13:48 UTC, Alexey-Lebedzeu commented on features/authentication_view/lib/src/ui/components/signup.dart
> +  TextEditingController emailController = TextEditingController();
final

2023-08-14 10:29 UTC, merged